baseURL = "https://shibadog.github.io/"
languageCode = "ja-jp"
title = "shibadog site"
theme = "hermit"

[author]
  name = "shibadog"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02T15:04:00-0700"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/shiba_dog"

  [[params.social]]
    name = "github"
    url = "https://github.com/shibadog"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about-hugo/"
    weight = 20

